---
- name: Remove nginx if present
  ansible.builtin.apt:
    name: nginx
    state: absent
    purge: yes
  ignore_errors: yes

- name: Install Apache
  apt:
    name: apache2
    state: present
    update_cache: yes
  notify: restart apache

- name: Install PHP
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes

- name: Deploy test PHP page
  ansible.builtin.copy:
    dest: /var/www/html/index.php
    content: "<?php phpinfo(); ?>"
    owner: www-data
    group: www-data
    mode: '0644'

- name: Install MySQL client
  ansible.builtin.apt:
    name: mysql-client
    state: present
    update_cache: yes
